In [47]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [48]:
from datetime import datetime, timedelta

def convert_mixed_time(x):
    
    try:
        # Excel decimal time
        if isinstance(x, float) or '.' in str(x):
            seconds = float(x) * 24 * 60 * 60
            return (datetime.min + timedelta(seconds=seconds)).time()
        
        # Normal HH:MM format
        return datetime.strptime(str(x), '%H:%M').time()
    
    except:
        return pd.NaT

In [49]:
Zomato = pd.read_csv('C:\\Users\\visha\\Downloads\\Datasets\\Zomato\\Zomato.csv' , encoding = 'latin-1')
Zomato.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [74]:
Zomato.isnull().sum()

ID                               0
Delivery_person_ID               0
Delivery_person_Age              0
Delivery_person_Ratings          0
Restaurant_latitude              0
Restaurant_longitude             0
Delivery_location_latitude       0
Delivery_location_longitude      0
Order_Date                       0
Time_Orderd                      0
Time_Order_picked              831
Weather_conditions               0
Road_traffic_density             0
Vehicle_condition                0
Type_of_order                    0
Type_of_vehicle                  0
multiple_deliveries              0
Festival                         0
City                             0
Time_taken (min)                 0
dtype: int64

In [59]:
Zomato['Delivery_person_Age'] = Zomato['Delivery_person_Age'].fillna(Zomato['Delivery_person_Age'].median())
Zomato['Delivery_person_Ratings'] = Zomato['Delivery_person_Ratings'].fillna(Zomato['Delivery_person_Ratings'].mean())
Zomato.dropna(subset=['Time_Orderd'], inplace=True)
Zomato['Weather_conditions']= Zomato['Weather_conditions'].fillna(Zomato['Weather_conditions'].mode()[0])
Zomato['Road_traffic_density'] = Zomato['Road_traffic_density'].fillna(Zomato['Road_traffic_density'].mode()[0])
Zomato['multiple_deliveries'] = Zomato['multiple_deliveries'].fillna(Zomato['multiple_deliveries'].median())
Zomato['Festival'] = Zomato['Festival'].fillna(Zomato['Festival'] == 'NO')
Zomato['City'] = Zomato['City'].fillna(Zomato['City'].mode()[0])

In [52]:
Zomato.duplicated().sum()

np.int64(0)

In [60]:
Zomato.info()

<class 'pandas.DataFrame'>
Index: 43423 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           43423 non-null  str
 1   Delivery_person_ID           43423 non-null  str
 2   Delivery_person_Age          43423 non-null  float64
 3   Delivery_person_Ratings      43423 non-null  float64
 4   Restaurant_latitude          43423 non-null  float64
 5   Restaurant_longitude         43423 non-null  float64
 6   Delivery_location_latitude   43423 non-null  float64
 7   Delivery_location_longitude  43423 non-null  float64
 8   Order_Date                   43423 non-null  datetime64[us]
 9   Time_Orderd                  43423 non-null  object
 10  Time_Order_picked            42592 non-null  object
 11  Weather_conditions           43423 non-null  str
 12  Road_traffic_density         43423 non-null  str
 13  Vehicle_condition            43423 non-null  int64
 14  Type_of_order                43423 non-null  str
 15  Type_of_vehicle              43423 non-null  str
 16  multiple_deliveries          43423 non-null  int64
 17  Festival                     43423 non-null  object
 18  City                         43423 non-null  str
 19  Time_taken (min)             43423 non-null  int64
dtypes: datetime64[us](1), float64(6), int64(3), object(3), str(7)
memory usage: 7.0+ MB

In [71]:
Zomato[Zomato['Time_Order_picked'].isnull()]

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
66,0x4b7f,HYDRES13DEL03,26.0,4.7,17.431477,78.400350,17.491477,78.460350,2022-03-05,23:50:00,NaT,Fog,Low,1,Buffet,motorcycle,0,No,Metropolitian,10
92,0x3185,HYDRES19DEL03,25.0,4.8,17.458998,78.500366,17.488998,78.530366,2022-03-26,23:55:00,NaT,Cloudy,Low,1,Snack,scooter,1,No,Urban,19
155,0x51e4,VADRES18DEL01,30.0,4.1,0.000000,0.000000,0.070000,0.070000,2022-04-04,23:50:00,NaT,Fog,Low,0,Snack,motorcycle,0,No,Metropolitian,43
157,0x1dac,CHENRES07DEL03,33.0,4.5,13.081878,80.248519,13.171878,80.338519,2022-03-04,23:45:00,NaT,Stormy,Low,2,Drinks,electric_scooter,1,No,Metropolitian,19
316,0x26d4,HYDRES05DEL03,32.0,4.9,17.433809,78.386744,17.523809,78.476744,2022-03-18,23:55:00,NaT,Sandstorms,Low,1,Buffet,scooter,1,No,Metropolitian,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45237,0x14ca,JAPRES03DEL03,28.0,4.1,26.913483,75.803139,26.943483,75.833139,2022-03-07,23:50:00,NaT,Windy,Low,0,Buffet,motorcycle,0,No,Metropolitian,21
45352,0x6a9b,SURRES16DEL01,26.0,4.9,21.160437,72.774209,21.270437,72.884209,2022-03-31,23:50:00,NaT,Cloudy,Low,0,Snack,motorcycle,0,No,Metropolitian,21
45520,0x1889,HYDRES01DEL02,26.0,4.5,17.410371,78.437225,17.540371,78.567225,2022-03-25,23:50:00,NaT,Fog,Low,0,Buffet,motorcycle,0,No,Metropolitian,24
45526,0x3781,JAPRES13DEL03,35.0,4.9,26.846156,75.802300,26.876156,75.832300,2022-03-09,23:50:00,NaT,Sunny,Low,1,Snack,scooter,0,No,Urban,17
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,2022-03-11,23:50:00,NaT,Cloudy,Low,1,Drinks,scooter,0,No,Metropolitian,16

In [55]:
Zomato['Time_Orderd'] = (
    Zomato['Time_Orderd']
    .apply(convert_mixed_time)
)

In [56]:
Zomato['Time_Order_picked'] = (
    Zomato['Time_Order_picked']
    .apply(convert_mixed_time)
)

In [80]:
Zomato.replace('NaN ', np.nan, inplace=True)
Zomato.replace('NULL', np.nan, inplace=True)
Zomato.replace('', np.nan, inplace=True)
Zomato.replace('NaT', np.nan, inplace=True)

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,2022-02-12,21:55:00,22:10:00,Fog,Jam,2,Snack,motorcycle,3,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,2022-02-13,14:55:00,15:05:00,Stormy,High,1,Meal,motorcycle,1,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,2022-03-04,17:30:00,17:40:00,Sandstorms,Medium,1,Drinks,scooter,1,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,2022-02-13,09:20:00,09:30:00,Sandstorms,Low,0,Buffet,motorcycle,0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,2022-02-14,19:50:00,20:05:00,Fog,Jam,1,Snack,scooter,1,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,11:35:00,11:45:00,Windy,High,1,Meal,motorcycle,0,No,Metropolitian,32
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,2022-02-16,19:55:00,20:10:00,Windy,Jam,0,Buffet,motorcycle,1,No,Metropolitian,36
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,2022-03-11,23:50:00,NaT,Cloudy,Low,1,Drinks,scooter,0,No,Metropolitian,16
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,2022-03-07,13:35:00,13:40:00,Cloudy,High,0,Snack,motorcycle,1,No,Metropolitian,26
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,2022-03-02,17:10:00,17:15:00,Fog,Medium,2,Snack,scooter,1,No,Metropolitian,36

In [83]:
Zomato.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weather_conditions             0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken (min)               0
dtype: int64

In [82]:
Zomato.dropna(
    subset=['Time_Orderd', 'Time_Order_picked'],
    inplace=True
)

In [57]:
Zomato['multiple_deliveries'] = (Zomato['multiple_deliveries'].astype(int))

In [58]:
Zomato['Order_Date'] = pd.to_datetime(Zomato['Order_Date'],dayfirst=True)

In [85]:
Zomato.info()

<class 'pandas.DataFrame'>
Index: 42592 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           42592 non-null  str
 1   Delivery_person_ID           42592 non-null  str
 2   Delivery_person_Age          42592 non-null  float64
 3   Delivery_person_Ratings      42592 non-null  float64
 4   Restaurant_latitude          42592 non-null  float64
 5   Restaurant_longitude         42592 non-null  float64
 6   Delivery_location_latitude   42592 non-null  float64
 7   Delivery_location_longitude  42592 non-null  float64
 8   Order_Date                   42592 non-null  datetime64[us]
 9   Time_Orderd                  42592 non-null  object
 10  Time_Order_picked            42592 non-null  object
 11  Weather_conditions           42592 non-null  str
 12  Road_traffic_density         42592 non-null  str
 13  Vehicle_condition            42592 non-null  int64
 14  Type_of_order                42592 non-null  str
 15  Type_of_vehicle              42592 non-null  str
 16  multiple_deliveries          42592 non-null  int64
 17  Festival                     42592 non-null  object
 18  City                         42592 non-null  str
 19  Time_taken (min)             42592 non-null  int64
dtypes: datetime64[us](1), float64(6), int64(3), object(3), str(7)
memory usage: 6.8+ MB

In [86]:
Zomato.describe()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Vehicle_condition,multiple_deliveries,Time_taken (min)
count,42592.000000,42592.000000,42592.000000,42592.000000,42592.000000,42592.000000,42592,42592.000000,42592.000000,42592.000000
mean,29.553461,4.635383,17.245409,70.772336,17.466509,70.835519,2022-03-13 16:41:07.392937,1.001268,0.752207,26.411204
min,20.000000,2.500000,-30.902872,0.000000,0.010000,0.010000,2022-02-11 00:00:00,0.000000,0.000000,10.000000
25%,25.000000,4.500000,12.933298,73.170283,12.986229,73.280937,2022-03-04 00:00:00,0.000000,0.000000,19.000000
50%,30.000000,4.700000,18.551440,75.898497,18.633626,76.002574,2022-03-15 00:00:00,1.000000,1.000000,26.000000
75%,35.000000,4.900000,22.732225,78.046106,22.785207,78.107044,2022-03-27 00:00:00,2.000000,1.000000,33.000000
max,39.000000,5.000000,30.914057,88.433452,31.054057,88.563452,2022-04-06 00:00:00,2.000000,3.000000,54.000000
std,5.750807,0.310719,7.701990,21.133834,7.339571,21.134049,NaN,0.816582,0.568948,9.399325

In [87]:
Clean_Zomato = Zomato.to_csv('C:\\Users\\visha\\Downloads\\Datasets\\Zomato\\Clean_Zomato.csv', index=False)

In [88]:
Clean_Zomato = pd.read_csv('C:\\Users\\visha\\Downloads\\Datasets\\Zomato\\Clean_Zomato.csv')

In [104]:
Clean_Zomato['Order_Date'] = pd.to_datetime(
    Clean_Zomato['Order_Date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [105]:
Clean_Zomato.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weather_conditions             0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken (min)               0
Order Hour                     0
Pickup Hour                    0
dtype: int64

Additional Columns

Order Hour Column

In [96]:
Clean_Zomato['Order Hour'] = pd.to_datetime(Clean_Zomato['Time_Orderd'].astype(str)).dt.hour

C:\Users\visha\AppData\Local\Temp\ipykernel_7972\669286863.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Clean_Zomato['Order Hour'] = pd.to_datetime(Clean_Zomato['Time_Orderd'].astype(str)).dt.hour

Pickup Hour

In [97]:
Clean_Zomato['Pickup Hour'] = pd.to_datetime(Clean_Zomato['Time_Order_picked'].astype(str)).dt.hour

C:\Users\visha\AppData\Local\Temp\ipykernel_7972\703854533.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Clean_Zomato['Pickup Hour'] = pd.to_datetime(Clean_Zomato['Time_Order_picked'].astype(str)).dt.hour

Day Name

In [107]:
Clean_Zomato['Day_Name'] = (
    Clean_Zomato['Order_Date']
    .dt.day_name()
)

Weekend

In [108]:
Clean_Zomato['Weekend'] = Clean_Zomato['Day_Name'].isin(['Saturday', 'Sunday'])

Delivery Distance

In [110]:
from math import radians, sin, cos, sqrt, atan2

def haversine(lat1, lon1, lat2, lon2):

    R = 6371

    lat1, lon1, lat2, lon2 = map(
        radians,
        [lat1, lon1, lat2, lon2]
    )

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        sin(dlat / 2)**2
        + cos(lat1)
        * cos(lat2)
        * sin(dlon / 2)**2
    )

    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    return R * c

Clean_Zomato['Delivery_Distance_km'] = Clean_Zomato.apply(
    lambda x: haversine(
        x['Restaurant_latitude'],
        x['Restaurant_longitude'],
        x['Delivery_location_latitude'],
        x['Delivery_location_longitude']
    ),
    axis=1
)

Delivery Speed

In [111]:
Clean_Zomato['Delivery_Speed'] = (
    Clean_Zomato['Delivery_Distance_km']
    / (Clean_Zomato['Time_taken (min)'] / 60)
)

Traffic Level Category

In [112]:
Clean_Zomato['High Traffic'] = Clean_Zomato['Road_traffic_density'].isin(['High', 'Jam'])

Rating Category

In [113]:
def rating_category(rating):
    if rating >= 4.5:
        return 'Excellent'
    elif rating >= 4:
        return 'Good'
    else:
        return 'Average'
    
    Clean_Zomato['Rating Category'] = Clean_Zomato['Delivery_person_Ratings'].apply(rating_category)

Delivery Time Category

In [115]:
def delivery_category(x):
    if x < 20:
        return 'Fast'
    elif x < 40: 
        return 'Average'
    else:
        return 'Slow'
    
Clean_Zomato['Delivery Category'] = Clean_Zomato['Time_taken (min)'].apply(delivery_category)

Peak Hour Flag

In [118]:
Clean_Zomato['Peak Hour'] = (Clean_Zomato['Order Hour'].between(12, 14) | Clean_Zomato['Order Hour'].between(19, 21))

In [119]:
Sorted_Zomato = Clean_Zomato.to_csv ('C:\\Users\\visha\\Downloads\\Datasets\\Zomato\\Sorted_Zomato.csv', index=False)

In [120]:
Sorted_Zomato = pd.read_csv('C:\\Users\\visha\\Downloads\\Datasets\\Zomato\\Sorted_Zomato.csv')

## Questions

In [122]:
Sorted_Zomato['City'].value_counts()

City
Metropolitian    32995
Urban             9441
Semi-Urban         156
Name: count, dtype: int64